### ISSUE TITLE
Correct behaviour on non-200 return codes.

### ISSUE THREAD

**Issue by tjconcept** [paylike/php-api#13]
A user has pointed out there's a bug here:
https://github.com/paylike/php-api/blob/master/Paylike/Adapter.php#L78

The `||` should probably have been an `&&`. I would instead suggest:

```php
200 <= $httpCode && $httpCode <= 299
```

That being said, we should probably return something more detailed instead of just returning false so the user has a chance to debug. I don't know if throwing is the right thing in PHP, but we should research that.

**Comment by tjconcept** [comment]
Fixed @ionutcalara?

**Comment by ionutcalara** [comment]
Yes, this was fixed.
