### ISSUE TITLE
parseResponse error in CurlClient

### ISSUE THREAD

**Issue by rasmussyberg** [paylike/php-api#20]
When sending a capture to a endpoint on an account that is not yet validated, the server will as expected send an 403 error Forbidden. 
However this is not handled by the PHP API and the application stops with an error. 

in CurlClient.php line 240
--
at CurlClient->handleApiError('', 403, array('Server' => 'nginx', 'Date' => 'Thu, 19 Jul 2018 16:33:08 GMT', 'Transfer-Encoding' => 'chunked', 'Connection' => 'keep-alive', 'X-Request-ID' => '8c31a91a8d84aa70115f1170a7f06896'), null)in CurlClient.php line 161
at CurlClient->parseResponse('', 403, array('Server' => 'nginx', 'Date' => 'Thu, 19 Jul 2018 16:33:08 GMT', 'Transfer-Encoding' => 'chunked', 'Connection' => 'keep-alive', 'X-Request-ID' => '8c31a91a8d84aa70115f1170a7f06896'))in CurlClient.php line 127
at CurlClient->request('POST', 'transactions/{SOME ID}/captures', array('amount' => {SOME AMOUNT}))in Transactions.php line 57

The API should expect different status codes, and not always expect a valid response.

**Comment by ionutcalara** [comment]
Hi there, do you mean you would expect the api the gracefully handle the exception instead of letting the developer implementing it do it?

**Comment by tjconcept** [comment]
I assume the error is catch-able as exemplified here: https://github.com/paylike/php-api#error-handling.

**Comment by ionutcalara** [comment]
I am closing this for now, as the error is catch-able, and I am not sure what issues you are having @rasmussyberg, please come back if this didn't clarify the issue for you.
