### ISSUE TITLE
Wrapper support for "lines" endpoint missing

### ISSUE THREAD

**Issue by JensKirk** [paylike/php-api#29]
Hi :-)

Can you improve your wrapper so it can be used for tracking payouts / transfers to the bank of the webshop owner each week or so?

We need this for booking entries into our accounting system so weekly payouts / transfers can be booked automatically.

Thank you :-)

**Comment by ionutcalara** [comment]
Hi @JensKirk, sure, I will add this, and it should be part of an update by the end of the week.

**Comment by ionutcalara** [comment]
The lines endpoint has been added in the PHP API wrapper in version 1.0.6, and it's accessible under `$paylike->merchants()->lines()`
