### ISSUE TITLE
Listing all Merchants: "You are correctly authenticated but do not have access"

### ISSUE THREAD

**Issue by JensKirk** [paylike/php-api#34]
Hi :-)

When doing this:
`$merchants = PayLike::Client()->merchants()->find($appID);`

I get the error message:
`You are correctly authenticated but do not have access.`

I want to list all merchants that we have on our reseller account and as the appID I am using the ID that we got when we created the reseller account via a shell command. The reseller account that is showing all the merchants when doing a login at your UI.

I have also tried using a App ID from a random merchant just to see what would happen and it said this instead:
`Endpoint not found.`

So my first approach was more correct but what am I missing here? :-)

Thank you :-)

**Comment by ionutcalara** [comment]
Hi @JensKirk this might be a permission issue, I will get back to you after the weekend after I consult with the team. Have a nice weekend!

**Comment by ionutcalara** [comment]
Hi @JensKirk while your login works to see all the merchants, app keys are initially linked to one merchant only. To link all of them you can use this endpoint: https://github.com/paylike/api-docs#add-app-to-a-merchant but this is not part of the paylike PHP API wrapper yet. 

I will look into adding this to the php wrapper and let you know when that is ready.

**Comment by JensKirk** [comment]
Okay :-) Thank you :-)

**Comment by ionutcalara** [comment]
Hi @JensKirk the last update to the wrapper add supports for apps. It works similar to lines:

```php 
$all_apps = $merchants->apps()->find($merchant_id,$args);
$merchants->apps()->add($merchant_id,$app_id);
$merchants->apps()->revoke($merchant_id,$app_id);
```

I will close this ticket but feel free to reopen if you still have issues.

**Comment by JensKirk** [comment]
Thank you :-) You are the best! :-D

**Comment by JensKirk** [comment]
I am getting different errors like:

`Call to undefined method Paylike\Endpoint\Apps::find()`

But changing to fetch() does work.

And:
`Call to undefined method Paylike\Endpoint\Apps::add()`

**Comment by ionutcalara** [comment]
Hi @JensKirk you need to use `Paylike\Endpoint\Merchant\Apps` and not `Paylike\Endpoint\Apps` . Try that and let me know if you still have issues.

**Comment by JensKirk** [comment]
So far my code is the following but I am still getting the mentioned error:

```
		$apps = PayLike::Client()->merchants()->apps()->find($merchantID);
		
		foreach ($apps as $app) {
			PayLike::Client()->merchants()->apps()->add($merchantID, $app["id"]);
		}
		
		try {
			$merchants = PayLike::Client()->merchants()->find($resellerID); <--- PLEASE NOTE THE SUPER ADMIN ID
		}
		catch(Exception $e) {
  			echo $e->getMessage();
  		}
```

What am I doing wrong?

I just want to get a list of all merchants so the system has easy access to them all (without loading them all from another system).

The code above still has to add the merchantIDs one by one but that too does not seem to work as desired :-)

**Comment by ionutcalara** [comment]
Hi, @JensKirk the way I see it, every time a merchant is created you need to have the id. So it depends how you create it. 

Once you have that id, you should add that merchant to your app key. 

Both the merchant id and the app key has to be known. After you add the merchant, you get get all the merchants added to a certain app key. 

``` PHP 
$merchant_id = 'merchant-id-to-be-added';
$app_id = 'the-app-id-you-use';

$client = new Paylike($app_id);
// add merchant
$client->merchants()->apps()->add($merchant_id,$app_id);

//list all merchants for your key
$merchants = $client->merchants()->find($app_id);
```

Let me know if the above works for you.
