### ISSUE TITLE
Improve the SDK: Add merchants to affiliate agreement in an easy and automatic way 

### ISSUE THREAD

**Issue by JensKirk** [paylike/php-api#36]
Hi :-)

Inspired by ticket #34 and the talk with your team can we also have the SDK extended so it be used for adding new merchants to the affiliate agreement that we as a web agency have with PayLike?

We just need some kind of easy and auto way to add them - perhaps after then are created their account or have something inserted in their signup via an url so they get connected to the agreement after they have signed up.

This will save us a lot of work when we really invite our clients and the future ones to PayLike.

The best solution would be something like giving them an url which add their account to the agreement while signing up or after :-)

**Comment by tjconcept** [comment]
Hi Jens,

Assuming you already have a partner app with us, for which you have the private key, I would suggest the following flow:

1. Create a new account (authenticated as your partner app)
2. Invite the client to the account by their email
3. Potentially, if needed, invite your client relationship manager's email as well

Wouldn't that work?

**Comment by JensKirk** [comment]
We are doing the already but I was thinking about something as an affilate url like:
https://paylike.dk/ref/webkonsulenterne

That we can give to our clients so they can sign up at paylike.dk themselves but we still get them under our super admin panel for later support and as part of the affilige agreement.

Your API can be used in this way but perhaps this is outside the scoop of your SDK?

**Comment by tjconcept** [comment]
Okay, got it.
It's definitely outside the scope of the SDK, but it could be a separate web application doing the logic behind the scenes.
I've created it internally and will close this issue.
