### ISSUE TITLE
Improve: Use sorting of the merchant lines?

### ISSUE THREAD

**Issue by JensKirk** [paylike/php-api#37]
Hi :-)

Could you improve the SDK (or talk to the endpoint programmers) so we can start using sorting of the merchant lines like this?

```
$params = array(
    'limit' => 100,
    'after' => Null,
    'before' => Null,
    'sort' => "desc OR asc", <--- IMPROVE?
    'filter' => array(
    	'successful' => true
    )
);

$lines = PayLike::Client()->merchants()->lines()->find($merchant["ID"], $params);
```

**Comment by tjconcept** [comment]
Hi Jens,

It's not currently supported by the API (otherwise than specifying *either* `after` or `before`). I've made a note of the idea though.
If you're subscribed to the integration mailing list, we'll let you know about updates.
