### ISSUE TITLE
missing composer.json

### ISSUE THREAD

**Issue by visitek** [paylike/php-api#8]
Temporary load through package type. It should be completely reimplemented

```json
    {
      "type": "package",
      "package": {
        "name": "paylike/paylike",
        "version": "1.0.0",
        "source": {
          "url": "https://github.com/paylike/php-api",
          "type": "git",
          "reference": "master"
        },
        "autoload": {
          "classmap": [
            "Paylike/"
          ]
        }
      }
    }
```

**Comment by ionutcalara** [comment]
Hi there, i am not sure i understand what you mean, this isn't yet available via packagist, i was thinking about adding it, could you tell me if this is what you are finding as an issue? The fact that this isn't on packagist?

**Comment by visitek** [comment]
Yes it is, because by this configuration it fetches master without release tag ... There should be release versions to fetch it from packagist.
